services:
  - type: web
    name: security-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/vulnerable-web-app/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

